Repository Eat-pizza-quickly/Jari-otte, pull requests merged in 2024-11, with the labels that each got.

#60 feat: S3 를 이용한 콘서트 이미지 업로드 구현
  concert-service/build.gradle
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ImageController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/ImageFile.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/ImageResponse.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/ImageException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ImageService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/ImageUtil.java
  concert-service/src/main/resources/application.yml
Labels: BE, ✨ feat

#62 feat: 카프카 도입
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/KafkaConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SeatReservationEvent.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/KafkaEventProducer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
Labels: BE, ✨ feat

#65 여러 공연 페이징 조회를 구현했습니다.
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/S3Config.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ConcertController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/resources/logback-concert.xml
Labels: BE, ✨ feat

#67 Elasticsearch JsoFormat yyyy-MM-dd'T'HH:mm:ss 변경
  elastic-search/src/main/java/com/sparta/elasticsearch/entity/ConcertSearch.java
Labels: BE, ✨ feat

#69 feat: 비동기적으로 예매 정보 DB에 저장 구현
  concert-service/docker-compose.yml
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/KafkaEventProducer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/KafkaConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/KafkaEventProducer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
  concert-service/src/main/resources/application.yml
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/config/KafkaConfig.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/controller/ReservationController.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/service/ReservationService.java
  reservation-service/src/main/resources/application.yml
Labels: BE, ✨ feat

#71 refactor: Elasticsearch 마이그레이션 콘서트 서비스
  concert-service/build.gradle
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/JacksonConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ConcertController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/SearchTermController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SearchAutoTitleDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SearchConcertResponseDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/SearchAutocompleteDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/SearchConcertListDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/SearchTermRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
  concert-service/src/main/resources/application.yml
  elastic-search/.gitattributes
  elastic-search/.gitignore
  elastic-search/build.gradle
  elastic-search/gradle/wrapper/gradle-wrapper.jar
  elastic-search/gradle/wrapper/gradle-wrapper.properties
  elastic-search/gradlew
  elastic-search/gradlew.bat
  elastic-search/settings.gradle
  elastic-search/src/main/java/com/sparta/elasticsearch/ElasticSearchApplication.java
  elastic-search/src/main/java/com/sparta/elasticsearch/common/advice/ApiResponse.java
  elastic-search/src/main/java/com/sparta/elasticsearch/repository/SearchTermRepository.java
  elastic-search/src/main/resources/application.yml
  elastic-search/src/main/resources/static/index.html
  elastic-search/src/test/java/com/sparta/elasticsearch/ElasticSearchApplicationTests.java
Labels: BE, ✨ feat

#76 fix: Elasticsearch 의존성 버전 문제 해결
  concert-service/build.gradle
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
Labels: 🔥 bug, BE

#77 feat: Elasticsearch 콘서트 생성 시 인덱스 저장
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
Labels: BE, ✨ feat

#78 feat: 좌석조회시 대기열 구현
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/QueueController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/SeatController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/ErrorResponse.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/QueueResponse.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/RestControllerAdvice.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/InvalidReservationFlowException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/RedisException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/RequestLimitExceededException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/SeatAlreadyReservedException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/UserNotInQueueException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/QueueRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/SeatReservationCode.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/QueueService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/RedisUtil.java
Labels: BE, ✨ feat

#79 feat: Elasticsearch 고도화
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchIndexConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/SearchTermController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SearchAutoTitleDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
  concert-service/src/main/resources/settings/mappings.json
  concert-service/src/main/resources/settings/settings.json
Labels: BE, ✨ feat

#83 feat: "잔여 좌석 수" DB에 스케쥴링으로 반영하기
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/ConcertServiceApplication.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/scheduler/SeatSyncScheduler.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
Labels: BE, ✨ feat

#85 feat: 이메일 비동기 인증 실패 시 retry 추가
  user-service/build.gradle
  user-service/src/main/java/com/eatpizzaquickly/userservice/UserServiceApplication.java
  user-service/src/main/java/com/eatpizzaquickly/userservice/service/EmailService.java
Labels: BE, ✨ feat

#91 feat: Elasticsearch DB 자동 동기화, 트랜잭션 분리
  concert-service/build.gradle
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/SearchTermRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
  concert-service/src/main/resources/application.yml
  concert-service/src/main/resources/settings/mappings.json
Labels: BE, ✨ feat

#94 refactor: 서비스 쿼리 유틸 클래스로 분리, DTO 변환 유틸 클래스로 분리, 커스텀 예외처리
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchIndexConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchInitializer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/RestControllerAdvice.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/AutocompleteException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/ConcertSearchException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/ElasticsearchIndexException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/QueryBuilder.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/ResultProcessor.java
Labels: BE, 🔨 refactor

#95 feat: 예매 내역, 결제 내역 조회 기능 추가
  reservation-service/build.gradle
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/config/QueryDslConfig.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/controller/PaymentController.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/dto/response/PaymentSimpleResponse.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/entity/Payment.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/repository/PaymentQueryDslRepository.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/repository/PaymentQueryDslRepositoryImpl.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/repository/PaymentRepository.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/service/PaymentService.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/controller/ReservationController.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/dto/ReservationResponseDto.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/repository/ReservationRepository.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/service/ReservationService.java
Labels: BE, ✨ feat

#98 fix: Elasticsearch ApiGateway JwtFilter, SecurityConfig 오타 수정
  api-gateway/src/main/java/com/eatpizzaquickly/apigateway/common/config/JwtFilter.java
  api-gateway/src/main/java/com/eatpizzaquickly/apigateway/common/config/SecurityConfig.java
Labels: BE, ✨ feat

#102 fix: 리뷰 유저 FeignClient 수정
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/review/client/user/UserResponseDto.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/review/client/user/UserServiceClient.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/review/service/ReviewService.java
Labels: BE, ✨ feat

#104 refactor: `ObjectMapper` 리팩토링
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/KafkaEventConsumer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/JsonUtil.java
  concert-service/src/main/resources/application.yml
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/config/JacksonConfig.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/util/JsonUtil.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/client/KafkaEventConsumer.java
  reservation-service/src/main/resources/application.yml
Labels: BE, 🔨 refactor

#108 feat: 카프카 트랜잭션 설정 추가
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/KafkaConfig.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/config/KafkaConfig.java
Labels: BE, ✨ feat

#113 feat: Elasticsearch 수정, 시큐리티 수정, JWT 수정
  api-gateway/src/main/java/com/eatpizzaquickly/apigateway/common/config/JwtFilter.java
  api-gateway/src/main/java/com/eatpizzaquickly/apigateway/common/config/SecurityConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ConcertController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SearchConcertResponseDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
  concert-service/src/main/resources/settings/mappings.json
Labels: BE, ✨ feat

#117 feat: Elasticsearch 콘서트 포스터 URL 저장 (인덱스X)
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SearchConcertResponseDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/resources/settings/mappings.json
Labels: BE, ✨ feat

#118 refactor: coupon batch no offset으로 변경
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/coupon/batch/CouponBatchConfig.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/coupon/batch/FeignUserCouponReader.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/coupon/client/CouponServiceClient.java
  coupon-service/src/main/java/com/eatpizzaquickly/couponservice/controller/CouponBatchController.java
  coupon-service/src/main/java/com/eatpizzaquickly/couponservice/repository/UserCouponRepository.java
  coupon-service/src/main/java/com/eatpizzaquickly/couponservice/service/CouponBatchService.java
Labels: BE, 🔨 refactor

#121 feat: 인기 공연 조회 로컬 캐시 도입
  concert-service/build.gradle
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/ConcertServiceApplication.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/RedisCachePublisher.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/RedisCacheSubscriber.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/CacheConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/RedisConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ConcertController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/QueueRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertCacheService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/RedisUtil.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/ResultProcessor.java
Labels: BE, ✨ feat

#124 feat: 스케쥴링으로 매주 인기 공연 초기화 구현 (#100)
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/common/client/ConcertClient.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/scheduler/ConcertScheduler.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ConcertController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
Labels: BE, ✨ feat

#125 Feat/#87
  batch-service/build.gradle
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/common/ApiResponse.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/common/client/ConcertClient.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/coupon/batch/CouponBatchScheduler.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/common/BatchConstant.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/common/SettlementBatchRunner.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/config/DataSourceConfig.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/config/PagingQueryProviderConfig.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/config/RowMapperConfig.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/config/SettlementBatchConfig.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/config/SettlementBatchScheduler.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/dto/request/HostIdRequestDto.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/dto/request/PaymentRequestDto.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/dto/response/ConcertHostResponseDto.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/entity/TempPayment.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/incrementer/redoIdIncrementer.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/listener/ItemProcessorExecutionLogging.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/listener/ItemReaderExecutionLogging.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/listener/ItemWriterExecutionLogging.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/processor/PaymentProcessor.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/reader/PaymentReader.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/writer/HostPointWriter.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/settlement/writer/PaymentWriter.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/ConcertController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/request/HostIdRequestDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/ConcertHostResponseDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/entity/ConcertSearch.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  elk/docker-compose.yml
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/controller/PaymentController.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/dto/request/PaymentRequestDto.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/dto/response/PaymentResponseDto.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/payment/service/PaymentService.java
  user-service/src/main/java/com/eatpizzaquickly/userservice/repository/HostBalanceJdbcRepository.java
  user-service/src/main/java/com/eatpizzaquickly/userservice/service/UserService.java
Labels: BE, 🔨 refactor

#130 refactor: 카프카 에러 핸들러, 노션 알림 로직 리팩터링
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/KafkaEventConsumer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/KafkaEventProducer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/reservation/ReservationCreateRequest.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/CustomKafkaErrorHandler.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/KafkaConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/event/ReservationCompensationEvent.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/SlackNotifier.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/config/CustomKafkaErrorHandler.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/config/KafkaConfig.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/util/SlackNotifier.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/client/KafkaEventConsumer.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/client/KafkaEventProducer.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/controller/ReservationController.java
Labels: BE, 🔨 refactor

#132 feat: `Redis`이용 좌석 조회 성능 향상
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/SeatController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SeatDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/request/SeatReservationRequest.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/response/ConcertDetailResponse.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/ConcertRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/ConcertService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/service/ReservationService.java
Labels: BE, ✨ feat

#134 feat: Elasticsearch 검색 최적화, 자동완성 정렬 기준 수정
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchIndexConfig.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/config/ElasticsearchInitializer.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/SearchTermController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/dto/SearchAutoTitleDto.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/exception/detail/ElasticsearchIndexException.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SearchService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/QueryBuilder.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/util/ResultProcessor.java
  concert-service/src/main/resources/settings/mappings.json
  concert-service/src/main/resources/settings/settings.json
Labels: BE, ✨ feat

#138 feat: 예매 취소시 좌석 원상 복구 구현
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/SeatController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/common/advice/ApiResponse.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/client/feign/ConcertClient.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/dto/SeatReservationRequest.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/service/ReservationService.java
Labels: BE, ✨ feat

#140 feat: 대기열 기능 스케줄러 기반 -> Redis Pub/Sub 기반으로 변경
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/common/client/ConcertClient.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/common/config/RedisConfig.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/client/WaitingQueueSubscriber.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/repository/QueueRedisRepository.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/repository/WaitingQueueRedisRepository.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/scheduler/QueueScheduler.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/service/WaitingQueueService.java
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/util/RedisUtil.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/client/RedisCachePublisher.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/controller/WaitingQueueController.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/WaitingQueueRedisRepository.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/SeatService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/service/WaitingQueueService.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/service/ReservationService.java
Labels: BE, ✨ feat

#142 feat: 리뷰 생성 부분 하나의 콘서트에서 여러개 좌석을 예매한 사용자 리뷰 권한 수정
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/reservation/repository/ReservationRepository.java
  reservation-service/src/main/java/com/eatpizzaquickly/reservationservice/review/service/ReviewService.java
Labels: BE, ✨ feat

#146 feat: 스레드 풀 기반으로 대기열 진행 기능 구현
  batch-service/src/main/java/com/eatpizzaquickly/batchservice/concert/service/WaitingQueueService.java
  concert-service/src/main/java/com/eatpizzaquickly/concertservice/repository/WaitingQueueRedisRepository.java
Labels: BE, ✨ feat
